version: '3.3'

services:
  prometheus:
    image: prom/prometheus:v2.47.2
    container_name: vintsentinisg-netology-prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    ports:
    - 9090:9090
    volumes:
    - ./prometheus:/etc/prometheus
    - prometheus-data:/prometheus
    networks:
    - vintsentinisg-my-netology-hw
    restart: always
  pushgateway:
    image: prom/pushgateway:v1.6.2
    container_name: vintsentinisg-netology-pushgateway
    ports:
    - 9091:9091
    networks:
    - vintsentinisg-my-netology-hw
    depends_on:
    - prometheus
    restart: unless-stopped
  grafana:
    image: grafana/grafana
    container_name: vintsentinisg-netology-grafana
    environment:
    GF_PATHS_CONFIG: /etc/grafana/custom.ini
    ports:
    - 80:3000
    volumes:
    - ./grafana:/etc/grafana
    - grafana-data:/var/lib/grafana
    networks:
    - vintsentinisg-my-netology-hw
    depends_on:
    - prometheus
    restart: unless-stopped
volumes:
  prometheus-data:
  grafana-data:
networks:
vintsentinisg-my-netology-hw:
driver: bridge
ipam:
  config:
  - subnet: 10.5.0.0/16
  - gateway: 10.5.0.1

